name: Build and Deploy Helios Nuget Packages

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**/*'
      - 'src/**/*'
      - 'test/**/*'
  push:
    branches:
      - main
    paths:
      - '.github/**/*'
      - 'src/**/*'
      - 'test/**/*'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Build Solution
        run: dotnet pack ./helios.sln -o ./pkg
      
      - name: Add Nuget Sources
        run: dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/derrysmith/index.json"
      
      - name: Push Nuget Packages
        run: dotnet nuget push ./pkg/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_TOKEN }} --source github